### ISSUE TITLE
请问有java版的吗？

### ISSUE THREAD

**Issue by AndroidKid19** [YummyLau/AndroidModularArchiteture#1]
请问有详细的使用文档吗？

**Comment by YummyLau** [comment]
暂时没有java版本的，都是使用kotlin。 目前期望的文档内容需要哪些，后面可以补上哈。

**Comment by AndroidKid19** [comment]
我这边项目暂时只需要webview 这个组件。所以需要单独集成这个。一些基础的使用如java 与 js交互等，这些是根据x5内核调用，还是jsbridge

**Comment by YummyLau** [comment]
x5只负责优化原生webview，java-js的交互还是使用jsbridge。  你的项目应该是java版本的，把整个模块复制过去，添加kotlin依赖就可以了，互相兼容的。另外这个是我去年开始集成写的java demo，你也可以参考下。 https://github.com/YummyLau/X5JsWebView
