### ISSUE TITLE
请问下集成了您框架下的 WebView 模块 ，但是没法办调用起来js  

### ISSUE THREAD

**Issue by androidCoderxiao** [YummyLau/AndroidModularArchiteture#2]
集成了您框架下的 WebView 模块 ，但是没法办调用起来js，直接用jsBrigde 可以调用起来 ，请问js 是否需要做一些修改 ，还有Demo 中是否有WebView模块的使用案例呢 ？谢谢您

**Comment by YummyLau** [comment]
> 集成了您框架下的 WebView 模块 ，但是没法办调用起来js，直接用jsBrigde 可以调用起来 ，请问js 是否需要做一些修改 ，还有Demo 中是否有WebView模块的使用案例呢 ？谢谢您

js模块做了修改，用于解析json。调试下你的demo是否有传递消息给js模块。demo目前只有打开网页的案例，使用js的模块没有放进去。你可以贴下你的流程代码或者写一下逻辑流程，我定位一下。

**Comment by androidCoderxiao** [comment]
目前是无法能接收到js模块的调用，我看到您这个WebViewJavascriptBridge.js文件 和jsBrigde的那个js文件 是有区别的。 所以想问下JS 端需要做什么修改才能正常调用起来

**Comment by YummyLau** [comment]
在WebViewJavascriptBridge里面实际只是调整了 _dispatchMessageFromNative 支持把string转化为obj而已。应该是你的部分流程没有写对。刚上传了一个demo，你可以参考最新demo，里面有native侧和h5侧的代码，你只需要clone下代码，然后选择 “debugModule” 运行就能看到了。
测试的核心代码在 debugModule下 com.debug.library.webview 包
核心x5Js库在 libWebView包
希望对你有帮助。

**Comment by YummyLau** [comment]
@androidCoderxiao 目前Js模块是否还有疑惑？

**Comment by androidCoderxiao** [comment]
实在抱歉，现在才看到您的回复，问题已经解决了，感谢您的耐心回复
