### ISSUE TITLE
sync工程会报错

### ISSUE THREAD

**Issue by seraphlee** [YummyLau/AndroidModularArchiteture#5]
Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

**Comment by YummyLau** [comment]
@seraphlee 看上去是你as版本不支持项目的gradle的版本。update一下As的版本哦

**Comment by seraphlee** [comment]
已解决，多谢
