### ISSUE TITLE
集成了libWebview模块

### ISSUE THREAD

**Issue by yongyf** [YummyLau/AndroidModularArchiteture#6]
将对象用fastjson转json给前端 function.onCallBack(str)，前端不能解析报错了。[INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token o in JSON at position 1"，他们好像无法解析json.  ios可以。

**Comment by YummyLau** [comment]
> 将对象用fastjson转json给前端 function.onCallBack(str)，前端不能解析报错了。[INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token o in JSON at position 1"，他们好像无法解析json. ios可以。

这个str的解析，前端和移动端都约定好就行了。是否使用json都没有关系的。只要能按照格式解析就好了。
