### ISSUE TITLE
项目编译不过 CreateProcess error=206, 文件名或扩展名太长。

### ISSUE THREAD

**Issue by 0xByteLeon** [YummyLau/AndroidModularArchiteture#7]
Android studio 4.0

**Comment by YummyLau** [comment]
我还是as3.6.3,等我升级测试下。这个应该是IDE的问题

**Comment by YummyLau** [comment]
@DreamerLeon  [参考这个](https://stackoverflow.com/questions/49981137/android-studio-3-1-1-createprocess-error-206-the-filename-or-extension-is-too-l) 和你的设备OS有关联
