### ISSUE TITLE
module中dependencies和组件层申明中dependencies的区别

### ISSUE THREAD

**Issue by zhuxiaole** [YummyLau/AndroidModularArchiteture#8]
不好意思，咨询个问题。
module中dependencies和组件层申明中dependencies的区别是什么？怎么配置才合理？

**Comment by YummyLau** [comment]
从作用上看，module的dependencies是这个模块代码所需要引用的依赖，而组件内声明的dependencies是指该组件中sdk部分所需要引用的依赖，因为插件会检索组件内需要被打包成sdk(jar)的所有代码，这些代码如果用到外部依赖，需要在打包期间正确引用到这些依赖。

**Comment by zhuxiaole** [comment]
OK，了解了，谢谢
